// GENERATED BY scripts/generate-icons.mjs - DO NOT EDIT BY HAND.
// Regenerate with: npm run icons
// 147 of 1072 available icons.
// 5 fall back to the single-tone pack (brand marks).

import i_activity from './icons/two-tone/activity.svg?raw';
import i_add from './icons/two-tone/add.svg?raw';
import i_ai_heart_square from './icons/two-tone/ai-heart-square.svg?raw';
import i_ai_homepage from './icons/two-tone/ai-homepage.svg?raw';
import i_ai_sand_timer from './icons/two-tone/ai-sand-timer.svg?raw';
import i_ai_shape_triangle from './icons/two-tone/ai-shape-triangle.svg?raw';
import i_archive from './icons/two-tone/archive.svg?raw';
import i_arrow_down4 from './icons/two-tone/arrow-down4.svg?raw';
import i_arrow_forward from './icons/two-tone/arrow-forward.svg?raw';
import i_arrow_left4 from './icons/two-tone/arrow-left4.svg?raw';
import i_arrow_right4 from './icons/two-tone/arrow-right4.svg?raw';
import i_arrow_swap from './icons/two-tone/arrow-swap.svg?raw';
import i_arrow_up3 from './icons/two-tone/arrow-up3.svg?raw';
import i_bag from './icons/two-tone/bag.svg?raw';
import i_bell from './icons/two-tone/bell.svg?raw';
import i_book from './icons/two-tone/book.svg?raw';
import i_book_saved from './icons/two-tone/book-saved.svg?raw';
import i_bookmark from './icons/two-tone/bookmark.svg?raw';
import i_box from './icons/two-tone/box.svg?raw';
import i_building from './icons/two-tone/building.svg?raw';
import i_calendar from './icons/two-tone/calendar.svg?raw';
import i_calendar_tick from './icons/two-tone/calendar-tick.svg?raw';
import i_call from './icons/two-tone/call.svg?raw';
import i_card from './icons/two-tone/card.svg?raw';
import i_card_send from './icons/two-tone/card-send.svg?raw';
import i_category from './icons/two-tone/category.svg?raw';
import i_chart from './icons/two-tone/chart.svg?raw';
import i_chart_fail from './icons/two-tone/chart-fail.svg?raw';
import i_chart_success from './icons/two-tone/chart-success.svg?raw';
import i_check from './icons/two-tone/check.svg?raw';
import i_clock from './icons/two-tone/clock.svg?raw';
import i_close_circle from './icons/two-tone/close-circle.svg?raw';
import i_cloud from './icons/two-tone/cloud.svg?raw';
import i_cloud_connection from './icons/two-tone/cloud-connection.svg?raw';
import i_cloud_lightning from './icons/two-tone/cloud-lightning.svg?raw';
import i_code from './icons/two-tone/code.svg?raw';
import i_coffee from './icons/two-tone/coffee.svg?raw';
import i_copy from './icons/two-tone/copy.svg?raw';
import i_copy_success from './icons/two-tone/copy-success.svg?raw';
import i_cpu from './icons/two-tone/cpu.svg?raw';
import i_crown from './icons/two-tone/crown.svg?raw';
import i_cup from './icons/two-tone/cup.svg?raw';
import i_danger from './icons/two-tone/danger.svg?raw';
import i_data from './icons/two-tone/data.svg?raw';
import i_devices from './icons/two-tone/devices.svg?raw';
import i_direct_send from './icons/two-tone/direct-send.svg?raw';
import i_document_download from './icons/two-tone/document-download.svg?raw';
import i_document_text from './icons/two-tone/document-text.svg?raw';
import i_dollar_circle from './icons/two-tone/dollar-circle.svg?raw';
import i_drop from './icons/two-tone/drop.svg?raw';
import i_edit from './icons/two-tone/edit.svg?raw';
import i_export_arrow from './icons/two-tone/export-arrow.svg?raw';
import i_eye from './icons/two-tone/eye.svg?raw';
import i_eye_slash from './icons/two-tone/eye-slash.svg?raw';
import i_filter from './icons/two-tone/filter.svg?raw';
import i_flag from './icons/two-tone/flag.svg?raw';
import i_flash from './icons/two-tone/flash.svg?raw';
import i_ghost from './icons/two-tone/ghost.svg?raw';
import i_gift from './icons/two-tone/gift.svg?raw';
import i_github from './icons/broken/github.svg?raw';
import i_glass from './icons/two-tone/glass.svg?raw';
import i_global from './icons/broken/global.svg?raw';
import i_global_search from './icons/two-tone/global-search.svg?raw';
import i_graph from './icons/two-tone/graph.svg?raw';
import i_grid from './icons/two-tone/grid.svg?raw';
import i_hashtag from './icons/two-tone/hashtag.svg?raw';
import i_heart from './icons/two-tone/heart.svg?raw';
import i_heart_circle from './icons/two-tone/heart-circle.svg?raw';
import i_hierarchy from './icons/two-tone/hierarchy.svg?raw';
import i_hierarchy_square from './icons/two-tone/hierarchy-square.svg?raw';
import i_home from './icons/two-tone/home.svg?raw';
import i_home_trend_down from './icons/two-tone/home-trend-down.svg?raw';
import i_home_trend_up from './icons/two-tone/home-trend-up.svg?raw';
import i_html from './icons/two-tone/html.svg?raw';
import i_image from './icons/two-tone/image.svg?raw';
import i_import_arrow from './icons/two-tone/import-arrow.svg?raw';
import i_info_circle from './icons/two-tone/info-circle.svg?raw';
import i_key from './icons/two-tone/key.svg?raw';
import i_key_square from './icons/two-tone/key-square.svg?raw';
import i_link from './icons/two-tone/link.svg?raw';
import i_lock from './icons/two-tone/lock.svg?raw';
import i_login from './icons/two-tone/login.svg?raw';
import i_logout from './icons/two-tone/logout.svg?raw';
import i_logout2 from './icons/two-tone/logout2.svg?raw';
import i_magicpen from './icons/two-tone/magicpen.svg?raw';
import i_menu from './icons/two-tone/menu.svg?raw';
import i_messages from './icons/two-tone/messages.svg?raw';
import i_minus_circle from './icons/two-tone/minus-circle.svg?raw';
import i_mirroring_screen from './icons/two-tone/mirroring-screen.svg?raw';
import i_mobile from './icons/two-tone/mobile.svg?raw';
import i_money from './icons/two-tone/money.svg?raw';
import i_monitor from './icons/two-tone/monitor.svg?raw';
import i_moon from './icons/two-tone/moon.svg?raw';
import i_more from './icons/two-tone/more.svg?raw';
import i_mouse from './icons/two-tone/mouse.svg?raw';
import i_mouse_circle from './icons/two-tone/mouse-circle.svg?raw';
import i_note from './icons/two-tone/note.svg?raw';
import i_notification from './icons/two-tone/notification.svg?raw';
import i_paperclip from './icons/two-tone/paperclip.svg?raw';
import i_path from './icons/two-tone/path.svg?raw';
import i_people from './icons/two-tone/people.svg?raw';
import i_presentation_chart from './icons/two-tone/presentation-chart.svg?raw';
import i_profile from './icons/two-tone/profile.svg?raw';
import i_profile_2user from './icons/two-tone/profile-2user.svg?raw';
import i_profile_circle from './icons/two-tone/profile-circle.svg?raw';
import i_programming_arrows from './icons/two-tone/programming-arrows.svg?raw';
import i_radio from './icons/two-tone/radio.svg?raw';
import i_receipt from './icons/two-tone/receipt.svg?raw';
import i_receipt_item from './icons/two-tone/receipt-item.svg?raw';
import i_refresh_circle from './icons/two-tone/refresh-circle.svg?raw';
import i_route_square from './icons/two-tone/route-square.svg?raw';
import i_scroll from './icons/two-tone/scroll.svg?raw';
import i_search from './icons/two-tone/search.svg?raw';
import i_search_normal from './icons/two-tone/search-normal.svg?raw';
import i_send from './icons/two-tone/send.svg?raw';
import i_setting from './icons/two-tone/setting.svg?raw';
import i_share from './icons/two-tone/share.svg?raw';
import i_shield from './icons/two-tone/shield.svg?raw';
import i_shield_cross from './icons/two-tone/shield-cross.svg?raw';
import i_shield_slash from './icons/two-tone/shield-slash.svg?raw';
import i_shield_tick from './icons/two-tone/shield-tick.svg?raw';
import i_slider from './icons/two-tone/slider.svg?raw';
import i_sms from './icons/two-tone/sms.svg?raw';
import i_sms_tracking from './icons/two-tone/sms-tracking.svg?raw';
import i_sort from './icons/two-tone/sort.svg?raw';
import i_star from './icons/two-tone/star.svg?raw';
import i_star2 from './icons/two-tone/star2.svg?raw';
import i_status from './icons/two-tone/status.svg?raw';
import i_status_up from './icons/two-tone/status-up.svg?raw';
import i_sun from './icons/two-tone/sun.svg?raw';
import i_tag from './icons/two-tone/tag.svg?raw';
import i_tag_user from './icons/two-tone/tag-user.svg?raw';
import i_text from './icons/two-tone/text.svg?raw';
import i_tick_circle from './icons/two-tone/tick-circle.svg?raw';
import i_tiktok from './icons/broken/tiktok.svg?raw';
import i_timer from './icons/two-tone/timer.svg?raw';
import i_trash from './icons/two-tone/trash.svg?raw';
import i_trend_down from './icons/two-tone/trend-down.svg?raw';
import i_trend_up from './icons/two-tone/trend-up.svg?raw';
import i_user from './icons/two-tone/user.svg?raw';
import i_user_circle_add from './icons/two-tone/user-circle-add.svg?raw';
import i_verify from './icons/two-tone/verify.svg?raw';
import i_wallet from './icons/two-tone/wallet.svg?raw';
import i_warning from './icons/two-tone/warning.svg?raw';
import i_whatsapp_logo from './icons/broken/whatsapp-logo.svg?raw';
import i_wifi from './icons/two-tone/wifi.svg?raw';
import i_youtube_logo from './icons/broken/youtube-logo.svg?raw';

export const rawIcons: Record<string, string> = {
	'activity': i_activity,
	'add': i_add,
	'ai-heart-square': i_ai_heart_square,
	'ai-homepage': i_ai_homepage,
	'ai-sand-timer': i_ai_sand_timer,
	'ai-shape-triangle': i_ai_shape_triangle,
	'archive': i_archive,
	'arrow-down4': i_arrow_down4,
	'arrow-forward': i_arrow_forward,
	'arrow-left4': i_arrow_left4,
	'arrow-right4': i_arrow_right4,
	'arrow-swap': i_arrow_swap,
	'arrow-up3': i_arrow_up3,
	'bag': i_bag,
	'bell': i_bell,
	'book': i_book,
	'book-saved': i_book_saved,
	'bookmark': i_bookmark,
	'box': i_box,
	'building': i_building,
	'calendar': i_calendar,
	'calendar-tick': i_calendar_tick,
	'call': i_call,
	'card': i_card,
	'card-send': i_card_send,
	'category': i_category,
	'chart': i_chart,
	'chart-fail': i_chart_fail,
	'chart-success': i_chart_success,
	'check': i_check,
	'clock': i_clock,
	'close-circle': i_close_circle,
	'cloud': i_cloud,
	'cloud-connection': i_cloud_connection,
	'cloud-lightning': i_cloud_lightning,
	'code': i_code,
	'coffee': i_coffee,
	'copy': i_copy,
	'copy-success': i_copy_success,
	'cpu': i_cpu,
	'crown': i_crown,
	'cup': i_cup,
	'danger': i_danger,
	'data': i_data,
	'devices': i_devices,
	'direct-send': i_direct_send,
	'document-download': i_document_download,
	'document-text': i_document_text,
	'dollar-circle': i_dollar_circle,
	'drop': i_drop,
	'edit': i_edit,
	'export-arrow': i_export_arrow,
	'eye': i_eye,
	'eye-slash': i_eye_slash,
	'filter': i_filter,
	'flag': i_flag,
	'flash': i_flash,
	'ghost': i_ghost,
	'gift': i_gift,
	'github': i_github,
	'glass': i_glass,
	'global': i_global,
	'global-search': i_global_search,
	'graph': i_graph,
	'grid': i_grid,
	'hashtag': i_hashtag,
	'heart': i_heart,
	'heart-circle': i_heart_circle,
	'hierarchy': i_hierarchy,
	'hierarchy-square': i_hierarchy_square,
	'home': i_home,
	'home-trend-down': i_home_trend_down,
	'home-trend-up': i_home_trend_up,
	'html': i_html,
	'image': i_image,
	'import-arrow': i_import_arrow,
	'info-circle': i_info_circle,
	'key': i_key,
	'key-square': i_key_square,
	'link': i_link,
	'lock': i_lock,
	'login': i_login,
	'logout': i_logout,
	'logout2': i_logout2,
	'magicpen': i_magicpen,
	'menu': i_menu,
	'messages': i_messages,
	'minus-circle': i_minus_circle,
	'mirroring-screen': i_mirroring_screen,
	'mobile': i_mobile,
	'money': i_money,
	'monitor': i_monitor,
	'moon': i_moon,
	'more': i_more,
	'mouse': i_mouse,
	'mouse-circle': i_mouse_circle,
	'note': i_note,
	'notification': i_notification,
	'paperclip': i_paperclip,
	'path': i_path,
	'people': i_people,
	'presentation-chart': i_presentation_chart,
	'profile': i_profile,
	'profile-2user': i_profile_2user,
	'profile-circle': i_profile_circle,
	'programming-arrows': i_programming_arrows,
	'radio': i_radio,
	'receipt': i_receipt,
	'receipt-item': i_receipt_item,
	'refresh-circle': i_refresh_circle,
	'route-square': i_route_square,
	'scroll': i_scroll,
	'search': i_search,
	'search-normal': i_search_normal,
	'send': i_send,
	'setting': i_setting,
	'share': i_share,
	'shield': i_shield,
	'shield-cross': i_shield_cross,
	'shield-slash': i_shield_slash,
	'shield-tick': i_shield_tick,
	'slider': i_slider,
	'sms': i_sms,
	'sms-tracking': i_sms_tracking,
	'sort': i_sort,
	'star': i_star,
	'star2': i_star2,
	'status': i_status,
	'status-up': i_status_up,
	'sun': i_sun,
	'tag': i_tag,
	'tag-user': i_tag_user,
	'text': i_text,
	'tick-circle': i_tick_circle,
	'tiktok': i_tiktok,
	'timer': i_timer,
	'trash': i_trash,
	'trend-down': i_trend_down,
	'trend-up': i_trend_up,
	'user': i_user,
	'user-circle-add': i_user_circle_add,
	'verify': i_verify,
	'wallet': i_wallet,
	'warning': i_warning,
	'whatsapp-logo': i_whatsapp_logo,
	'wifi': i_wifi,
	'youtube-logo': i_youtube_logo
};
