// GENERATED BY scripts/generate-image-dimensions.mjs - DO NOT EDIT BY HAND.
// Regenerate with: npm run images
// 41 images measured from static/.

export type ImageSize = { width: number; height: number };

const SIZES: Record<string, ImageSize> = {
	'/apple-touch-icon.png': { width: 180, height: 180 },
	'/apps/crown.png': { width: 1320, height: 2868 },
	'/apps/dishpoa.png': { width: 1320, height: 2868 },
	'/apps/future.png': { width: 1320, height: 2868 },
	'/apps/qailly.png': { width: 1320, height: 2868 },
	'/apps/status.png': { width: 1320, height: 2868 },
	'/apps/zidiplay.png': { width: 1320, height: 2868 },
	'/billmate_logo.png': { width: 1400, height: 1400 },
	'/blog/plan.jpg': { width: 1000, height: 667 },
	'/blog/skillkenya-1.jpg': { width: 1000, height: 654 },
	'/cline.png': { width: 4306, height: 2594 },
	'/crown-chambers.png': { width: 3020, height: 1810 },
	'/dev-cleaner.png': { width: 2708, height: 1862 },
	'/dishpoa.png': { width: 2704, height: 1690 },
	'/favicon-32x32.png': { width: 32, height: 32 },
	'/favicon-96x96.png': { width: 96, height: 96 },
	'/favicon.jpg': { width: 1762, height: 1754 },
	'/futurespace.png': { width: 2560, height: 1600 },
	'/icon-192.png': { width: 192, height: 192 },
	'/icon-512.png': { width: 512, height: 512 },
	'/icon-maskable-512.png': { width: 512, height: 512 },
	'/internlink.png': { width: 2560, height: 1600 },
	'/inventree.png': { width: 3024, height: 1964 },
	'/jestorm.png': { width: 2560, height: 1600 },
	'/kentom_website_banner.jpg': { width: 2100, height: 1305 },
	'/logo-dark.png': { width: 576, height: 596 },
	'/logo-light.png': { width: 576, height: 596 },
	'/market.png': { width: 2560, height: 1600 },
	'/mockup.jpg': { width: 3508, height: 1754 },
	'/namelogo.jpg': { width: 5279, height: 1754 },
	'/new/image-gsap.png': { width: 750, height: 750 },
	'/new/kentom-bg-main.png': { width: 3822, height: 2400 },
	'/qailly.png': { width: 3024, height: 1964 },
	'/scholarspace.png': { width: 2560, height: 1600 },
	'/Screenshot 2025-09-24 at 15.46.11.png': { width: 3024, height: 1964 },
	'/skillkenya.png': { width: 3024, height: 1624 },
	'/splitmate_logo.png': { width: 2362, height: 2362 },
	'/status-saver.png': { width: 2560, height: 1600 },
	'/steve-osoro-tom-full-image.png': { width: 4000, height: 6000 },
	'/steve-tom-half-image.png': { width: 4000, height: 3875 },
	'/zidiplay.png': { width: 3024, height: 1964 }
};

/**
 * Pixel size of an image served from static/, or null when it is unknown.
 * Callers must treat null as "omit the dimension tags" rather than guessing:
 * a wrong og:image:width is worse than an absent one, because a scraper will
 * lay the card out to the size we claim.
 */
export function imageSize(path: string | null | undefined): ImageSize | null {
	if (!path) return null;
	const clean = path.split('?')[0];
	return SIZES[clean] ?? null;
}
