/**
 * Builds src/lib/icons.generated.ts: the subset of the icon pack that this
 * site actually references.
 *
 * Icons come from the two-tone pack ($lib/icons/two-tone). The five brand marks
 * that pack does not carry (github, global, tiktok, whatsapp-logo,
 * youtube-logo) fall back to the older single-tone pack, which is correct:
 * a company logo should not be restyled into a two-tone glyph.
 *
 * The packs ship ~1000 SVGs each. Globbing one eagerly inlined every icon into
 * the client bundle (~1.3 MB in a single chunk) to render the few dozen the
 * site uses. This script scans the source for every reachable icon name and
 * emits static imports for just those, so Vite bundles nothing else.
 *
 * Run it after adding an icon: `npm run icons`.
 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, extname } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const PRIMARY = 'two-tone';
const FALLBACK = 'broken';

const listPack = (pack) =>
	readdirSync(join(ROOT, 'src/lib/icons', pack))
		.filter((f) => f.endsWith('.svg'))
		.map((f) => f.slice(0, -4));

// name -> pack it should be imported from, primary winning over fallback
const source = new Map();
for (const n of listPack(FALLBACK)) source.set(n, FALLBACK);
for (const n of listPack(PRIMARY)) source.set(n, PRIMARY);
const available = new Set(source.keys());

// every source file we might reference an icon from
const files = [];
(function walk(dir) {
	for (const e of readdirSync(dir, { withFileTypes: true })) {
		const p = join(dir, e.name);
		if (e.isDirectory()) {
			if (e.name !== 'icons') walk(p);
		} else if (
			['.svelte', '.ts', '.js'].includes(extname(e.name)) &&
			// Never scan our own output: it lists every icon it already contains,
			// so reading it back would keep stale icons alive on every run and no
			// icon could ever be dropped.
			e.name !== 'icons.generated.ts'
		) {
			files.push(p);
		}
	}
})(join(ROOT, 'src'));

// aliases are a public part of the icon API, so every target they can resolve
// to has to stay in the bundle even if no page names it directly today.
const iconsTs = readFileSync(join(ROOT, 'src/lib/icons.ts'), 'utf8');
const aliasBlock = iconsTs.split('const aliases')[1] ?? '';
const aliasTargets = [...aliasBlock.matchAll(/\w+\s*:\s*'([a-z0-9-]+)'/g)].map((m) => m[1]);

const keep = new Set(aliasTargets.filter((n) => available.has(n)));

// Broad net: any quoted string anywhere in the source that exactly matches an
// icon filename counts as a reference. This deliberately over-collects (a
// handful of unused icons cost a few hundred bytes each) because the failure
// mode of under-collecting is an icon silently rendering blank in production.
for (const f of files) {
	const text = readFileSync(f, 'utf8');
	for (const m of text.matchAll(/['"`]([a-z0-9-]{2,40})['"`]/g)) {
		if (available.has(m[1])) keep.add(m[1]);
	}
}

const names = [...keep].sort();
const ident = (n) => 'i_' + n.replace(/-/g, '_');

const out = `// GENERATED BY scripts/generate-icons.mjs - DO NOT EDIT BY HAND.
// Regenerate with: npm run icons
// ${names.length} of ${available.size} available icons.
// ${names.filter((n) => source.get(n) === FALLBACK).length} fall back to the single-tone pack (brand marks).

${names.map((n) => `import ${ident(n)} from './icons/${source.get(n)}/${n}.svg?raw';`).join('\n')}

export const rawIcons: Record<string, string> = {
${names.map((n) => `\t'${n}': ${ident(n)}`).join(',\n')}
};
`;

writeFileSync(join(ROOT, 'src/lib/icons.generated.ts'), out);
const fromFallback = names.filter((n) => source.get(n) === FALLBACK);
console.log(`icons.generated.ts: kept ${names.length} of ${available.size}`);
console.log(`  two-tone: ${names.length - fromFallback.length}`);
console.log(`  fallback: ${fromFallback.length} (${fromFallback.join(', ')})`);
